#!/usr/bin/env python3
"""Batch 2: original summaries for Omo Odù 56-110.
Run: python3 scripts/write-omo-summaries-2.py"""
import re, glob, os

S = {
56: ("A hidden depth meets the work of healing. The figure says that what is gestating inside you needs patient, proper care before it can come to full strength.",
     "Give recovery and slow-growing plans the time they need, and seek good counsel."),
57: ("Mystery gives way to clarity. Something kept in the dark for a long time is about to be explained, and a confused situation will become plain.",
     "Hold steady through the uncertainty; understanding is close."),
58: ("Quiet endurance carries a hidden project forward. Setbacks are real, but the work growing beneath the surface will succeed.",
     "Keep going without fanfare and let results speak when the time comes."),
59: ("Concealed effort is rewarded with sweetness. The figure promises that private discipline brings a blessing that you can share with others.",
     "Be thankful and generous with what you receive."),
60: ("The deep mystery is brought to a clean completion. The figure favours honesty, integrity and bringing hidden matters to a peaceful end.",
     "Act transparently and finish what you started with a clear conscience."),
61: ("A warning is attached to a bright opportunity. Blessings are available, but they depend on keeping promises and making the right offering.",
     "Pay what you owe, spiritually and practically, before moving ahead."),
62: ("Sacrifice meets mortality. The figure warns that careless action can bring loss, and urges care for the family and the elderly.",
     "Act prudently, protect the vulnerable, and make the offering that restores balance."),
63: ("Consequence is revealed through insight. The figure says that honest self-examination can turn a looming warning into a lesson learned in time.",
     "Look at your own conduct first and correct course early."),
64: ("A costly secret demands attention. Hidden matters carry consequences, and bringing them into the open prevents greater harm.",
     "Be truthful about what has been concealed and put things right."),
65: ("Danger and instability travel together. The figure advises humility and flexibility so that sudden change does not become a loss.",
     "Stay adaptable, avoid risky shortcuts, and keep your guard up."),
66: ("Pride invites a hard lesson. The figure warns that boasting after success can turn fortune around, and calls for restraint.",
     "Let humility temper achievement and avoid showing off."),
67: ("Conflict carries a price. The figure says that anger leads to injury, while honest speech and a willingness to sacrifice calm the situation.",
     "Settle disputes quickly and do not let temper make the decision."),
68: ("Hard work and offerings go hand in hand. The path ahead is clearable, but only if effort is paired with respect for spiritual duty.",
     "Work steadily, and honour your commitments to the Òrìṣà."),
69: ("A storm threatens, and a sacrifice shelters. The figure advises preparing for upheaval by making offerings and holding to principle.",
     "Protect what matters before trouble arrives."),
70: ("Resentment brings danger. The figure warns that jealousy can cause harm, and that sacrifice and restraint turn aside the threat.",
     "Do not nurse grudges, and guard against those who wish you ill."),
71: ("The body gives a warning. The figure links health to conduct, and advises treatment, patience and attention to what has been neglected.",
     "Take health problems seriously and treat them early."),
72: ("Clarity follows a cautionary lesson. After a period of trouble, the picture clears and the right course is revealed.",
     "Learn from what has happened and move forward with a clear mind."),
73: ("Hardship is survivable with perseverance. The figure promises eventual victory, provided you accept guidance and make the needed offering.",
     "Persist, and do not skip the steps that safeguard your progress."),
74: ("Sacrifice opens the way to sweetness. The figure says that what you give up in good faith returns as blessing.",
     "Give willingly and express gratitude for what comes back to you."),
75: ("A hard lesson ends in purity. The figure speaks of cleansing, moral integrity and a clean slate after proper atonement.",
     "Make things right and begin again with a clear conscience."),
76: ("Instability meets opportunity. The figure shows that light is available in a changing world, but only to those who stay humble and flexible.",
     "Adapt your plans, and stay modest while fortunes shift."),
77: ("Change reaches the ancestral realm. Old family patterns shift, and the figure asks you to honour tradition while adjusting to new circumstances.",
     "Respect the elders and remain open to necessary change."),
78: ("Shifting ground calls for self-knowledge. The figure says that knowing your own mind is the best protection when everything else is moving.",
     "Reflect honestly, and let your values steady your decisions."),
79: ("Change works in hidden ways. Transformation is underway beneath the surface, and the figure asks for patience with the process.",
     "Trust that something is shifting for the better, even if you cannot yet see it."),
80: ("Restless fortune meets warning. The figure advises caution during unstable times and recommends offerings to keep losses small.",
     "Avoid reckless decisions and protect what you have."),
81: ("Changing status tests character. The figure shows that rank and reputation can move quickly, and that humility keeps honour intact.",
     "Hold position lightly and treat others with respect."),
82: ("Volatility feeds conflict. The figure warns that rapid change can bring arguments, and that plain honest speech keeps peace.",
     "Communicate clearly and avoid reacting in the heat of the moment."),
83: ("Changing conditions call for tireless effort. The figure rewards those who adjust their methods while keeping the goal in sight.",
     "Stay flexible in method and firm in purpose."),
84: ("Double turbulence demands calm. The figure advises staying centred when events spin quickly and seeking shelter in sound principles.",
     "Keep your composure and avoid major decisions in the middle of the storm."),
85: ("Instability can breed resentment. The figure warns that frustration with change may turn into bitterness, and urges forgiveness.",
     "Let go of anger and focus on what you can control."),
86: ("Changes affect the body and health. The figure advises rest, regular care and patience during recovery.",
     "Look after your wellbeing while circumstances shift."),
87: ("Confusion gives way to understanding. After a restless stretch, the figure promises a clear view of what to do next.",
     "Wait for clarity, then act with confidence."),
88: ("Resilience turns upheaval into progress. The figure says that those who keep trying through shifting conditions finally win.",
     "Do not give up when plans change; adapt and continue."),
89: ("Change brings an unexpected blessing. The figure says that what looks like disruption may carry a gift, and calls for thanks.",
     "Welcome the new with gratitude and share what it brings."),
90: ("Restlessness settles into integrity. The figure suggests that stability is found through honest living, not through control of events.",
     "Build peace on honest conduct and let the rest follow."),
91: ("Honour meets light. The figure grants standing and favourable beginnings, and asks that leadership remain humble.",
     "Lead gracefully and credit those who helped you."),
92: ("Status is set against mortality. The figure reminds the proud that position is temporary and that respect for ancestors is lasting.",
     "Use your standing to serve and remember those who came before."),
93: ("Leadership needs self-knowledge. The figure says that real authority starts with an honest look at your own motives.",
     "Examine your motives before you ask others to follow you."),
94: ("Authority carries hidden depth. The figure suggests that a leader's strongest assets are often unseen and should not be displayed for show.",
     "Let quiet competence earn trust."),
95: ("Pride is a costly companion. The figure warns that boasting invites a lesson, and that sacrifice restores balance.",
     "Keep your words modest and your promises faithful."),
96: ("Power is unstable when pride grows. The figure says that status changes quickly for those who lose humility.",
     "Stay grounded and prepare for shifts in fortune."),
97: ("Pride meets conflict. The figure warns that arrogance produces quarrels, and that honest, measured speech prevents them.",
     "Choose words carefully, especially when you hold authority."),
98: ("Honour is earned by work. The figure says that standing grows through effort and perseverance rather than claims.",
     "Do the work, and let your reputation follow."),
99: ("A leader faces a storm. The figure advises calm, protective decisions when the group is shaken by sudden change.",
     "Steady those around you and protect the vulnerable."),
100: ("Pride attracts envy. The figure warns that visible success draws resentment, and that restraint is the best shield.",
      "Be discreet about your achievements and generous toward critics."),
101: ("Responsibility includes health. The figure ties leadership to caring for the body and for people under your care.",
      "Look after your own wellbeing and that of your dependants."),
102: ("Insight tempers authority. The figure says that clarity of mind lets a leader decide with fairness once confusion has passed.",
      "Wait for the full picture before judging."),
103: ("Perseverance restores honour. The figure promises that standing lost through setbacks can be regained through patient effort.",
      "Keep working steadily; your name will be rebuilt."),
104: ("Honour is sweetest when shared. The figure says that blessings grow when a leader is generous and grateful.",
      "Share credit and rewards with your community."),
105: ("Leadership ends well when it is clean. The figure praises integrity and a good legacy built on honesty.",
      "Act so that your name is remembered with respect."),
106: ("Truth walks into the light. The figure says that open honesty brings a fresh start, even when it begins as conflict.",
      "Speak truthfully and let the air clear."),
107: ("Hard truths touch the ancestors. The figure warns of family disputes and advises honest, fair settlement of inherited matters.",
      "Resolve family conflicts with fairness and respect."),
108: ("Honest speech joins self-awareness. The figure says that you can say hard things well only after you have looked honestly at yourself.",
      "Check your own part in a quarrel before you speak."),
109: ("A buried quarrel needs air. The figure says that what is left unsaid will grow, and it is wiser to address it early.",
      "Raise the difficult subject calmly before it hardens."),
110: ("Conflict has consequences. The figure warns that anger can lead to injury or loss, and that sacrifice and restraint bring peace.",
      "Cool tempers, make amends and pay what is owed."),
}

root = os.path.join(os.path.dirname(__file__), '..', 'content', 'odu-ifa')
for n, (ov, gd) in S.items():
    path = glob.glob(os.path.join(root, f'omo-odu-{n:03d}-*.md'))[0]
    txt = open(path, encoding='utf-8').read()
    m = re.match(r'^---\n(.*?)\n---\n(.*)$', txt, re.S)
    fm, body = m.group(1), m.group(2)
    title = re.search(r'^title:\s*"?(.*?)"?\s*$', fm, re.M).group(1)
    fm = re.sub(r'^excerpt:.*?(?=^pattern_right:)',
                'excerpt: "' + ov.replace('"', '\\"') + '"\n', fm, flags=re.S | re.M)
    infl = re.search(r'### Governing Influences\n.*?(?=\n### Guidance)', body, re.S).group(0)
    foot = re.search(r'^(?:- - -|---)\s*$.*', body, re.S | re.M).group(0)
    new = f'## {title}\n\n### Overview\n\n{ov}\n\n{infl}\n\n### Guidance\n\n{gd}\n\n{foot}'
    open(path, 'w', encoding='utf-8').write(f'---\n{fm}\n---\n{new}')
print('updated', len(S))
