#!/usr/bin/env python3
"""Insert original English summaries into the first 55 Omo Odù files.
Run: python3 scripts/write-omo-summaries.py
Each entry: number -> (overview, guidance). Edit freely and re-run."""
import re, glob, os

S = {
1: ("Light meets the threshold of the ancestors. This figure speaks of a bright beginning that must be built on respect for those who came before, and of potential that is only realised when it is rooted in lineage.",
    "Honour your ancestors before launching a new venture, and let gratitude steady your ambition."),
2: ("Clarity of purpose joins deep self-knowledge. The figure says that the success you seek is already in you, but you must look honestly inward to find where it is hidden.",
    "Spend time in reflection before acting. Seek truth about yourself first and the way outward will open."),
3: ("Open possibility enters a closed, mysterious space. Something promising is gestating and cannot be hurried; the light is present even where it is not yet visible.",
    "Be patient with projects still taking shape and protect them from premature exposure."),
4: ("Divine favour is tied to sacrifice. Blessings are available, but they follow a willingness to give something up and to keep promises made to the Òrìṣà.",
    "Make the offering or commitment you have been postponing, and keep your word."),
5: ("Fortune is bright but unstable. The figure warns that good luck can turn quickly, and that humility is what keeps a blessing in place.",
    "Stay modest in success and prepare for changing circumstances."),
6: ("Natural leadership is tested by pride. The figure grants honour and standing, then asks whether you can carry them without boasting.",
    "Lead by example, speak less of your achievements, and let your work speak for you."),
7: ("Truth is spoken into a heated situation. Light exposes what is wrong, and that can cause conflict before it brings peace.",
    "Say what must be said with care, and avoid answering anger with anger."),
8: ("Opportunity arrives with hard work attached. The way forward is open, but it must be cleared by effort, skill and perseverance.",
    "Take up your tools and work steadily; the path will respond to determination."),
9: ("A bright path crosses a whirlwind. Sudden change threatens plans, yet the figure promises protection to those who stay grounded.",
    "Expect disruption, keep your counsel, and hold on to your principles while things settle."),
10: ("Great promise is shadowed by ill will. Someone nearby may envy or resent your progress, and restraint is the best defence.",
    "Guard your plans from jealous eyes and do not repay malice with malice."),
11: ("The figure joins vitality with the call to heal. Good fortune depends on caring for the body and being patient with slow recovery.",
    "Attend to your health, seek proper treatment, and give healing the time it needs."),
12: ("Understanding follows a period of confusion. Truth that was hidden comes into view and brings a new sense of direction.",
    "Trust that answers are coming. Act once the picture is clear rather than in the fog."),
13: ("Success is delayed but not denied. A setback is only a stage; the figure confirms that persistence brings a hidden victory.",
    "Keep going through disappointment. Your effort is being rewarded in ways not yet visible."),
14: ("Abundance and gratitude walk together. The figure points to sweetness in life, and to a duty to share it generously.",
    "Give thanks openly and share your good fortune; generosity multiplies blessings."),
15: ("A pure beginning reaches maturity. The figure speaks of integrity, of wisdom that comes with age, and of work brought to completion.",
    "Act cleanly and honestly, and seek the counsel of elders to bring a matter to a good end."),
16: ("The unseen world presses toward the light. The ancestors bring a message and ask that it be turned into a living, practical beginning.",
    "Listen for guidance from elders and ancestors, then act on it with confidence."),
17: ("Ancestral memory meets inner sight. This figure says that the answers you seek come through honest self-examination and respect for the departed.",
    "Remember where you come from, and let that knowledge shape who you decide to be."),
18: ("An ending is quietly preparing a rebirth. Like a seed in the earth, something that seems finished is transforming out of sight.",
    "Do not mourn too long. Prepare for what is growing beneath the surface."),
19: ("Loss and consequence are close together. The figure warns of the cost of careless actions and of the need for offerings to protect the living.",
    "Make amends where needed and perform the sacrifice that restores balance."),
20: ("Change reaches the household of the ancestors. Old arrangements shift, and flexibility is the price of keeping peace in the family.",
    "Adapt to new circumstances in the family and hold tradition with an open hand."),
21: ("Prestige is tempered by mortality. Whatever honour you hold is temporary, and the figure urges humility and generosity with it.",
    "Use your position to serve others, since status will not last forever."),
22: ("Hard truths surface around loss or inheritance. Conflict may rise, and honesty with the family is what lets it settle.",
    "Resolve disputes openly and fairly, especially over what the departed have left behind."),
23: ("The path is cleared through effort and respect for the dead. Work and ritual are two parts of the same duty.",
    "Persevere in your labour and do not neglect your spiritual obligations."),
24: ("Turbulence stirs the realm of the ancestors. The figure warns of sudden upheaval and advises calm, protective action.",
    "Stay composed in a crisis and seek spiritual cover before making big decisions."),
25: ("Resentment threatens to harm the living. The figure advises restraint and reconciliation so that bitterness does not grow into loss.",
    "Let go of grudges and mend broken relationships while there is time."),
26: ("Sickness and the thin boundary of life appear together. The figure advises prompt care, patience and attention to the elderly and ill.",
    "Look after the sick, seek treatment early, and do not delay the healing."),
27: ("Clarity arrives after grief. The mist lifts and the figure shows a calmer path forward following a period of sorrow.",
    "Allow mourning its season, then step forward with renewed clarity."),
28: ("Endurance is rewarded after loss. Hard times are real, but the figure tells of a quiet triumph for those who do not give up.",
    "Keep faith through difficulty; your steady effort will outlast the setback."),
29: ("Sweetness comes out of endings. The figure speaks of blessings that follow sacrifice and of gratitude toward those who have passed.",
    "Give thanks to your ancestors and enjoy the good that their foundation has made possible."),
30: ("A life reaches its natural completion with dignity. The figure honours old age, a clean conscience and a peaceful transition.",
    "Live with integrity so that you may close each chapter in peace."),
31: ("Self-knowledge leads back to the source of light. This figure says that insight and opportunity belong together, and that inner honesty draws blessings in.",
    "Look inward with sincerity and let what you discover guide your next step."),
32: ("The inner eye turns toward the ancestors. Truth about yourself is tied to understanding your roots and the lives of those before you.",
    "Study your family history and reflect on how it shapes your character."),
33: ("Hidden things come to the surface slowly. The figure speaks of mysteries, secrets and truths that mature in the dark before being revealed.",
    "Be patient with what is still unclear and avoid forcing answers."),
34: ("Perception is challenged by consequence. The figure warns that ignoring the signs leads to a costly lesson, and that sacrifice can restore order.",
    "Pay attention to warnings, and act early to avoid avoidable losses."),
35: ("Insight meets instability. Changing circumstances demand that you see clearly, adjust quickly and remain humble.",
    "Stay observant and flexible, and do not cling to plans that no longer fit."),
36: ("Knowing oneself checks arrogance. The figure says that honest self-assessment protects against the pitfalls of pride and showing off.",
    "Measure yourself honestly and let your character, not your boasting, earn respect."),
37: ("Sharp truth cuts through confusion. The figure promises that honest vision settles conflict, even if the process is uncomfortable.",
    "Speak plainly and with insight, and accept that clarity can sting before it heals."),
38: ("Vision directs effort. The figure advises thinking carefully before acting so that hard work is spent on the right road.",
    "Plan first, then labour with determination; insight makes effort effective."),
39: ("Turmoil calls for a clear mind. When events are moving fast, self-knowledge is the anchor that keeps you safe.",
    "Remain calm in a crisis and trust your own judgement."),
40: ("Seeing through deceit protects you. The figure warns of hidden ill will and shows how awareness defuses it.",
    "Watch the motives of those near you, and respond with wisdom, not retaliation."),
41: ("Understanding the body and spirit supports healing. The figure links inner awareness to recovery and balance.",
    "Listen to your body and mind; rest and reflection are part of the cure."),
42: ("Confusion gives way to revelation. The figure promises that a clouded situation will be explained and a new light will dawn.",
    "Wait for understanding to arrive, and act decisively once it does."),
43: ("Self-belief carries you through setbacks. The figure says that inner conviction is what turns delay into eventual victory.",
    "Remember who you are when things look bleak, and keep working toward your goal."),
44: ("Wisdom brings sweetness. Knowing yourself leads to contentment, and the figure encourages gratitude for what you already have.",
    "Appreciate your blessings, and share the joy that comes from a clear conscience."),
45: ("Insight ripens into integrity. The figure honours a life lived honestly and suggests that self-knowledge reaches its fullest form in goodness.",
    "Live truthfully and trust that your character will carry you to a good conclusion."),
46: ("Mystery contains a gift. Something concealed or still developing holds the promise of light, if given time.",
    "Nurture what is not yet visible and trust that it will emerge in its own season."),
47: ("A hidden process meets the ancestral realm. The figure points to inherited patterns, transformation and the quiet work of renewal.",
    "Honour your lineage and allow necessary changes to unfold slowly."),
48: ("Depth is paired with insight. This figure advises looking beneath appearances, since what is concealed holds the meaning of the situation.",
    "Investigate carefully and do not trust surface impressions."),
49: ("Secrecy carries a price. The figure warns that hidden matters have consequences, and that offerings and honesty restore balance.",
    "Bring concealed problems into the open and make the necessary amends."),
50: ("Transformation proceeds through unsteady times. The figure suggests that change feels uncomfortable because something new is forming.",
    "Accept uncertainty as part of growth and stay humble while you adapt."),
51: ("Hidden strength must not turn into pride. The figure grants quiet power and cautions against displaying it for show.",
    "Let your capability be revealed through action rather than words."),
52: ("A concealed conflict demands honesty. The figure says that what is left unsaid will eventually erupt, so it is better to speak plainly.",
    "Address tensions early and truthfully before they grow."),
53: ("Slow, deep work is rewarded. The figure advises persistent effort on projects that are not yet visible to others.",
    "Keep working diligently; foundations laid in private will support later success."),
54: ("Stillness before the storm. The figure warns of coming upheaval and advises preparing quietly and protecting what is vulnerable.",
    "Prepare, secure what matters, and stay composed when change arrives."),
55: ("Hidden malice needs careful handling. The figure urges patience and discretion in dealing with someone whose intentions are unclear.",
    "Be discreet, avoid confrontation, and rely on prudence rather than suspicion."),
}

root = os.path.join(os.path.dirname(__file__), '..', 'content', 'odu-ifa')
for n, (ov, gd) in S.items():
    path = glob.glob(os.path.join(root, f'omo-odu-{n:03d}-*.md'))[0]
    txt = open(path, encoding='utf-8').read()
    m = re.match(r'^---\n(.*?)\n---\n(.*)$', txt, re.S)
    fm, body = m.group(1), m.group(2)
    title = re.search(r'^title:\s*"?(.*?)"?\s*$', fm, re.M).group(1)
    # excerpt: replace multi-line excerpt block
    fm = re.sub(r'^excerpt:.*?(?=^pattern_right:)',
                'excerpt: "' + ov.replace('"', '\\"') + '"\n', fm, flags=re.S | re.M)
    infl = re.search(r'### Governing Influences\n.*?(?=\n### Guidance)', body, re.S).group(0)
    foot = re.search(r'^(?:- - -|---)\s*$.*', body, re.S | re.M).group(0)
    new = (f'## {title}\n\n### Overview\n\n{ov}\n\n{infl}\n\n### Guidance\n\n{gd}\n\n{foot}')
    open(path, 'w', encoding='utf-8').write(f'---\n{fm}\n---\n{new}')
print('updated', len(S))
